[project]
name = "comfyui-input-thumbnails"
description = "A ComfyUI custom node that adds a fast, visual thumbnail gallery picker for browsing and selecting images from the input directory. Does not replace core Load Image."
version = "1.3.0"
license = { file = "LICENSE.txt" }

[project.urls]
Repository = "https://github.com/panjapongr/ComfyUI-InputThumbnails"

[tool.comfy]
PublisherId = "panjapong"
DisplayName = "ComfyUI Input Thumbnails"